/* base version: 2
 * ADDRESS: char *personal; char *mailbox; int group; struct address_t *next; unsigned is_idn : 1; unsigned idn_checked : 1;
 * BUFFER: char *data; char *dptr; size_t dsize; int destroy;
 * LIST: char *data; struct list_t *next;
 * ENVELOPE: ADDRESS *return_path; ADDRESS *from; ADDRESS *to; ADDRESS *cc; ADDRESS *bcc; ADDRESS *sender; ADDRESS *reply_to; ADDRESS *mail_followup_to; char *list_post; char *subject; char *real_subj; char *message_id; char *supersedes; char *date; char *x_label; BUFFER *spam; LIST *references; LIST *in_reply_to; LIST *userhdrs; unsigned int irt_changed : 1; unsigned int refs_changed : 1;
 * PARAMETER: char *attribute; char *value; struct parameter *next;
 * BODY: char *xtype; char *subtype; PARAMETER *parameter; char *description; char *form_name; long hdr_offset; off_t offset; off_t length; char *filename; char *d_filename; char *charset; CONTENT *content; struct body *next; struct body *parts; struct header *hdr; struct attachptr *aptr; signed short attach_count; time_t stamp; unsigned int type : 4; unsigned int encoding : 3; unsigned int disposition : 2; unsigned int use_disp : 1; unsigned int unlink : 1; unsigned int tagged : 1; unsigned int deleted : 1; unsigned int noconv : 1; unsigned int force_charset : 1; unsigned int is_signed_data : 1; unsigned int goodsig : 1; unsigned int warnsig : 1; unsigned int badsig : 1; unsigned int collapsed : 1; unsigned int attach_qualifies : 1;
 * HEADER: unsigned int security : 11; unsigned int mime : 1; unsigned int flagged : 1; unsigned int tagged : 1; unsigned int deleted : 1; unsigned int changed : 1; unsigned int attach_del : 1; unsigned int old : 1; unsigned int read : 1; unsigned int expired : 1; unsigned int superseded : 1; unsigned int replied : 1; unsigned int subject_changed : 1; unsigned int threaded : 1; unsigned int display_subject : 1; unsigned int recip_valid : 1; unsigned int active : 1; unsigned int trash : 1; unsigned int zhours : 5; unsigned int zminutes : 6; unsigned int zoccident : 1; unsigned int searched : 1; unsigned int matched : 1; unsigned int attach_valid : 1; unsigned int collapsed : 1; unsigned int limited : 1; size_t num_hidden; short recipient; int pair; time_t date_sent; time_t received; off_t offset; int lines; int index; int msgno; int virtual; int score; ENVELOPE *env; BODY *content; char *path; char *tree; struct thread *thread; short attach_total; int refno; void *data; char *maildir_flags;
 */
#define HCACHEVER 0x2a4c178f
