/* this is an autogenerated file.  edit patchlist.sh instead. */
#include "config.h"

#include <stdio.h>
#include <stdlib.h>

#include "mutt.h"

void mutt_print_patchlist (void)
{
  puts ("patch-1.5.11.as.echo.1");
  puts ("patch-1.5.19.sidebar.20090308.txt");
}
